### ISSUE TITLE
add x11 as dependency

### ISSUE THREAD

**Issue by sidorares** [AndrewSwerlick/node-remote#1]
node-x11 is now on npm ( http://search.npmjs.org/#/x11 ) , you can add it to your package.json

**Comment by AndrewSwerlick** [comment]
Thanks sidorares, did you just do that? I don't remember seeing it this weekend. I'll add and update things tomorrow evening.

**Comment by sidorares** [comment]
Couple of days ago
I'll try to push packages to rpm weekly

Can I look at your WarpPointer code?

**Comment by AndrewSwerlick** [comment]
Should be done. Thanks for pointing this out
