### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by tneil** [AndrewSwerlick/node-remote#4]
I've been trying to get this code up and running on my Win7 box and I'm getting a **ECONNREFUSED** error right on the xManager.createXManger() call is happening

https://github.com/AndrewSwerlick/node-remote/blob/master/remote-server.js#L10

Any ideas on what might be causing this?  I can try and get you as much diagnostics information as you need

**Comment by AndrewSwerlick** [comment]
This really only supports linux as is. It's relying on a c++ library written by a third party that drives the XWindowServer used for display on linux machines. I'm not really maintaining this anymore either as it was pretty much a labor day experiment, that I haven't looked at in a few years.

**Comment by tneil** [comment]
Ok, thanks for the response Andrew.. I had wondered if it was a platform specific limitation
